//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concessionaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opcionaisveiculo
    {
        public int IDopVe { get; set; }
        public int IDVeiculo { get; set; }
        public int IDOpcional { get; set; }
    
        public virtual Opcional Opcional { get; set; }
        public virtual Veiculo Veiculo { get; set; }
    }
}
